name: Daily Scraping Job

on:
  schedule:
    - cron: "0 3 * * *"  # Runs daily at 3 AM UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run scraper
        run: |
          python run_scraper.py

      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'eivindlovoll@hotmail.com'
          git add reactapp/public/finn_listings.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update finn_listings.json" && git push)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 